# Generated by Django 6.0.8 on 2026-08-05 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup_company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demovideoandimage',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='progressvideoandimage',
            name='campaign',
        ),
    ]
