# Generated by Django 6.0.8 on 2026-08-05 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_rasing', '0002_initial'),
        ('startup_company', '0002_remove_demovideoandimage_campaign_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='current_amount',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='video_url',
        ),
        migrations.AddField(
            model_name='campaign',
            name='demo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startup_company.demovideoandimage'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startup_company.progressvideoandimage'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='short_code',
            field=models.CharField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='name',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='fundtransaction',
            name='transaction_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reportcampaign',
            name='name',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
