# Generated by Django 6.0.8 on 2026-09-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='Traction_describtion',
        ),
    ]
